# Generated by Django 2.2.4 on 2019-08-09 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crowdfunder', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='username',
            field=models.CharField(default='', max_length=300),
            preserve_default=False,
        ),
    ]
