# Generated by Django 2.1.5 on 2019-08-11 06:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crowdfunder', '0004_donation_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='reward',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='donations_reward', to='crowdfunder.Reward'),
        ),
    ]
