# Generated by Django 2.1.5 on 2019-08-11 06:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crowdfunder', '0005_auto_20190811_0639'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reward',
            name='level',
        ),
        migrations.AddField(
            model_name='reward',
            name='minimum_donation',
            field=models.FloatField(null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
