# Generated by Django 2.1.5 on 2019-08-11 06:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crowdfunder', '0006_auto_20190811_0642'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='fund_goal',
            field=models.FloatField(default=100, verbose_name=django.core.validators.MinValueValidator(100)),
            preserve_default=False,
        ),
    ]
