# Generated by Django 2.1.5 on 2019-08-11 07:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crowdfunder', '0007_project_fund_goal'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='current_funds',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='fund_goal',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(100)]),
        ),
    ]
