# Generated by Django 2.1.5 on 2019-08-11 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crowdfunder', '0008_auto_20190811_0705'),
    ]

    operations = [
        migrations.AddField(
            model_name='reward',
            name='name',
            field=models.TextField(default='Yes'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='project',
            name='current_funds',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
