# Generated by Django 2.1.5 on 2019-08-11 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crowdfunder', '0009_auto_20190811_0750'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reward',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
