# Generated by Django 2.2.3 on 2019-08-12 19:06

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('crowdfunder', '0010_auto_20190811_0751'),
    ]

    operations = [
        migrations.CreateModel(
            name='Update',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(validators=[django.core.validators.MinLengthValidator(10), django.core.validators.MaxLengthValidator(500)])),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='updates_project', to='crowdfunder.Project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='updates_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
