# Generated by Django 2.2.4 on 2019-08-12 19:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('crowdfunder', '0013_auto_20190812_1918'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profilex',
            name='description',
        ),
        migrations.RemoveField(
            model_name='profilex',
            name='email',
        ),
        migrations.RemoveField(
            model_name='profilex',
            name='total_donations',
        ),
        migrations.CreateModel(
            name='TestModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_moed', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
