# Generated by Django 2.2.4 on 2019-08-12 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crowdfunder', '0016_auto_20190812_1932'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='total_donations',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
