# Generated by Django 2.2.3 on 2019-08-12 21:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crowdfunder', '0011_update'),
        ('crowdfunder', '0017_auto_20190812_1934'),
    ]

    operations = [
    ]
